name: "Create draft release"

on:
  push:
    branches:
      - master

jobs:
  update_draft_release:
    runs-on: windows-latest
    steps:
      - uses: svenstaro/upload-release-action@v2
        with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: dist\hamiltonian_cycle.exe
            asset_name: hamiltonian_cycle
            tag: ${{ github.ref }}
            overwrite: true
            body: 'Release created by GitHub Actions'